name: Preview Deployment

on:
  push:
    branches-ignore:
      - main
      - renovate/*

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - id: previous-sha
        run: 'echo "sha=$(git rev-list -n 1 ${{ github.ref }}^)" >> $GITHUB_OUTPUT'

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          base: "${{ steps.previous-sha.outputs.sha }}"
          filters: |
            frontend:
              - 'pkgs/frontend/**'
            backend:
              - 'pkgs/backend/**'

  frontend:
    name: Frontend
    environment: dev
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11.3.0

      - name: Install dependencies and build
        working-directory: pkgs/frontend
        run: |
          echo "${{ secrets.DOTENV }}" > .env
          pnpm install --prod --frozen-lockfile
          NODE_ENV=development pnpm build

      - name: Deploy to Cloudflare Workers
        id: cloudflare
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: pkgs/frontend
          command: versions upload

  backend:
    name: Backend
    environment: dev
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11.3.0

      - name: Install dependencies and build
        working-directory: pkgs/backend
        run: |
          echo "${{ secrets.DOTENV }}" > .env
          pnpm install --prod --frozen-lockfile
          NODE_ENV=development pnpm build

      - name: Deploy to Cloudflare Workers
        id: cloudflare
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: pkgs/backend
          command: versions upload
